### PR TITLE
feat: remove search index tool

### PR DESCRIPTION
**Pull request by yuye-aws**
### Description
Remove search index tool in the current repo: https://github.com/opensearch-project/skills/issues/294
 
### Issues Resolved
Remove search index tool in the current repo: https://github.com/opensearch-project/skills/issues/294
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by yuye-aws** [comment]
@ylwu-amzn Please help attach backport 2.x label.

**Comment by yuye-aws** [comment]
@yuye-aws This PR is ready for review now.

**Comment by xinyual** [comment]
Why we want to remove this tool?

**Comment by ylwu-amzn** [comment]
@yuye-aws CI failed, fix it?

**Comment by yuye-aws** [comment]
> @yuye-aws CI failed, fix it?

Adding a new commit to fix the CI error. You can start reviewing this PR while waiting for the CI results.

**Comment by yuye-aws** [comment]
Please merge this PR after this one: https://github.com/opensearch-project/ml-commons/pull/2356

**Review by ylwu-amzn — APPROVED** [review]

**Review by mingshl — APPROVED** [review]

**Pull request merged**
